version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-java
      args:
        - JAVA_VERSION=17
    ports:
      - "8092:8092"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_recruitment
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=andreykuz2002
    depends_on:
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile-mysql
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
